# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure CXP FTA Internal Subscription DALARS(60d45c6e-19a3-49d3-9b40-c349d97761da)'
    subscriptionId: '60d45c6e-19a3-49d3-9b40-c349d97761da'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'speechtotext-rg'
    location: 'Australia East'
    templateLocation: 'URL of the file'
    csmFileLink: 'azuredeploy-nolinked.json'
    deploymentMode: 'Validation'
    deploymentOutputs: 'AzureDeployOutputs'
- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'